### ISSUE TITLE
Tag editor changing case

### ISSUE THREAD

**Issue by Moilleadoir** [tari01/odio#2]
When I paste a track title into the tag editor it changes the case of the title. For some languages (often in classical pieces) this is just completely wrong. It’s a strange obsession of English pop music to make almost everything start with a capital, but it’s really not the best thing to do without asking the user.

**Example**
“An Wasserflüssen Babylon BWV 653b à 5 voci con 2 tastiere e pedale doppio” becomes 
“An Wasserflüssen Babylon BWV 653b à 5 Voci con 2 Tastiere E Pedale Doppio”

Also, I’m copying these track titles from the temp wav files. Will Odio be able to tag these automatically in future (since it obviously has the information)?

**Comment by tari01** [comment]
@Moilleadoir Thanks for reporting this.

Although automatic title-casing can be a great time-saver for most titles in e.g. English, Spanish or German, I agree it can also be a nuisance for other languages - sometimes I also have to retype some characters. To prevent Odio from constantly asking the user what he wants, I suggest we add an option to the settings dialog where people can toggle this feature.

As for automatically pulling in tags from source files, I consciously chose not to do it - source tags can contain loads of unwanted data, plus they would would have to be stored separately, so it would be nearly impossible to track what goes where whenever a user splits/joins tracks, drops something from the list, etc.

Using a clean file is so bad: If your album is on allmusic.com, open it in your browser, copy the URL of the page, and click the "Get tag" button in the tag editor.

There are also some undocumented features for manual tagging, for instance: you can right-click any input field, and select "Insert filename" from the menu.

**Comment by tari01** [comment]
@Moilleadoir 

I have commited a fix for this issue, and released version 21.2.28. Please come back any time should you find a bug or have a feature request.

Fixed via https://github.com/tari01/odio/commit/08aa1d600f0cfde6a51d587a28c98f34b9406c86
