### ISSUE TITLE
Crash when opening .iso

### ISSUE THREAD

**Issue by kybos** [tari01/odio#4]
Hi,

I've just installed odio from your ppa on Mint 19.3.
When trying to open a SACD iso (both through the Open-button and drag/drop), the programm crashes:

$ odio
(odio:27382): Pango-CRITICAL **: 21:36:10.527: pango_layout_set_width: assertion 'layout != NULL' failed
(odio:27382): Pango-CRITICAL **: 21:36:10.527: pango_layout_set_alignment: assertion 'layout != NULL' failed
(odio:27382): Pango-CRITICAL **: 21:36:10.527: pango_layout_set_text: assertion 'layout != NULL' failed
Segmentation fault (core dumped)

Let me know if can do something to help with the problem.
Thanks.

**Comment by kybos** [comment]
Just tried to command line converter (odio-sacd). The crash occurrs there as well:

Odio SACD v20.5.11
-----------------
Command-line decoder

Segmentation fault (core dumped)


BTW: The iso itself seems ok, I am able to open/play and convert it with foobar (in Wine).

**Comment by tari01** [comment]
Thanks for reporting this. Could you please upload the ISO file somewhere and send me the link via E-mail so I could test it?

**Comment by kybos** [comment]
Mail sent.

**Comment by tari01** [comment]
@kybos 

I have tested your file with the latest versions of the applications and everything seems to work fine. Try:
```
sudo apt update
sudo apt upgrade
```
You should now have:

- libodisacd 21.4.23
- odio-sacd 21.1.9
- odio 21.4.30

Please report back how it went.

**Comment by kybos** [comment]
Thanks for checking.
Yes, I have older versions of the tools (20.x...).
apt update does not help.
Is the PPA wrong?
deb http://ppa.launchpad.net/robert-tari/main/ubuntu bionic main

Just looked in Launchpad: There seem to be no newer versions for Mint 19.3 (which is based on Ubuntu 18.04) in this PPA.

**Comment by tari01** [comment]
> Just looked in Launchpad: There seem to be no newer versions for Mint 19.3 (which is based on Ubuntu 18.04) in this PPA.

Yes, I only publish my apps as back as the last LTS. You can do two things:

- Download the .deb packages for 20.04 and install them manually (The might still work with 18.04 - or not)
- Install from source (very easy, instructions on each component's web page)

I am closing this because the bug is not in the source, but you can still leave comments here.

**Comment by kybos** [comment]
I could compile the current libodiosacd which fixed the crash.
Current odio does not work here as it depends on GTK 3.24.

**Comment by tari01** [comment]
> I could compile the current libodiosacd which fixed the crash.

I'm glad it worked out!

> Current odio does not work here as it depends on GTK 3.24.

You can try if the old Odio works with the new libodiosacd. Unfortunately, I cannot really  provide much support for this mixture. Those 20.x.x components are seriously outdated...
